
default: &default
  adapter: postgresql
  encoding: unicode
  username: katemrrr
  password: 123456
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: data-storage_development

test:
  <<: *default
  database: data-storage_test

production:
  <<: *default
  database: data-storage_production
  username: data-storage
  password: <%= ENV['DATA-STORAGE_DATABASE_PASSWORD'] %>
